# Generated by Django 3.0.5 on 2021-05-19 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2021-05-19')),
                ('due_date', models.DateField(default='2021-05-19')),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='NoteApp.Category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
