name: Note4me

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: admin1
          POSTGRES_PASSWORD: admin1
        ports:
          - "5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p Note4me/htmlcov
      - name: Configure GPG Key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          passphrase: ${{ secrets.SECRET_PWD }}
      - name: Reveal secrets
        env:
          SECRET_PWD: ${{ secrets.SECRET_PWD }}
        run: |
          sudo apt install git-secret
          git secret tell olahsymbo@gmail.com
          git secret reveal -p $(echo $SECRET_PWD | sed 's/./& /g')
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Coverage report
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report
      - name: Django Testing
        run: python3 manage.py test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: Note4me/htmlcov/
