name: Note4me

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p hypelytics-ml/htmlcov
      - run: echo hello > hypelytics-ml/htmlcov/coverage-text.html
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
#      - name: Lint with flake8
#        run: |
#           pip install flake8
#           flake8
      - name: Coverage report
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report
      - name: Django Testing
        run: python3 manage.py test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: hypelytics-ml/htmlcov/coverage-text.html
